// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDailyHistory = `-- name: CreateDailyHistory :exec
INSERT INTO daily_history (
    daily_id, user_id, title, description, difficulty, due_date, time_zone, status, missed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'MISSED', $8
)
`

type CreateDailyHistoryParams struct {
	DailyID     pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	TimeZone    string
	MissedAt    pgtype.Timestamptz
}

func (q *Queries) CreateDailyHistory(ctx context.Context, arg CreateDailyHistoryParams) error {
	_, err := q.db.Exec(ctx, createDailyHistory,
		arg.DailyID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
		arg.TimeZone,
		arg.MissedAt,
	)
	return err
}

const getDamageAmount = `-- name: GetDamageAmount :one
SELECT damage_amount FROM difficulty_rewards WHERE difficulty = $1
`

func (q *Queries) GetDamageAmount(ctx context.Context, difficulty string) (int32, error) {
	row := q.db.QueryRow(ctx, getDamageAmount, difficulty)
	var damage_amount int32
	err := row.Scan(&damage_amount)
	return damage_amount, err
}

const listCompletedExpiredDailies = `-- name: ListCompletedExpiredDailies :many
SELECT id, due_date, time_zone
FROM dailies
WHERE status = 'COMPLETED' AND due_date < $1
ORDER BY due_date ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListCompletedExpiredDailiesParams struct {
	Before    pgtype.Timestamptz
	BatchSize int32
}

type ListCompletedExpiredDailiesRow struct {
	ID       pgtype.UUID
	DueDate  pgtype.Timestamptz
	TimeZone string
}

// Selects up to `batch_size` COMPLETED dailies whose due_date has passed,
// locking them with SKIP LOCKED so concurrent worker instances don't collide.
func (q *Queries) ListCompletedExpiredDailies(ctx context.Context, arg ListCompletedExpiredDailiesParams) ([]ListCompletedExpiredDailiesRow, error) {
	rows, err := q.db.Query(ctx, listCompletedExpiredDailies, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedExpiredDailiesRow
	for rows.Next() {
		var i ListCompletedExpiredDailiesRow
		if err := rows.Scan(&i.ID, &i.DueDate, &i.TimeZone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExpiredDailies = `-- name: ListPendingExpiredDailies :many
SELECT id, user_id, title, description, difficulty, due_date, time_zone
FROM dailies
WHERE status = 'PENDING' AND due_date < $1
ORDER BY due_date ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListPendingExpiredDailiesParams struct {
	Before    pgtype.Timestamptz
	BatchSize int32
}

type ListPendingExpiredDailiesRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	TimeZone    string
}

// Selects up to `batch_size` PENDING dailies whose due_date has passed,
// locking them with SKIP LOCKED so concurrent worker instances don't collide.
func (q *Queries) ListPendingExpiredDailies(ctx context.Context, arg ListPendingExpiredDailiesParams) ([]ListPendingExpiredDailiesRow, error) {
	rows, err := q.db.Query(ctx, listPendingExpiredDailies, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingExpiredDailiesRow
	for rows.Next() {
		var i ListPendingExpiredDailiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.DueDate,
			&i.TimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCompletedDaily = `-- name: ResetCompletedDaily :exec
UPDATE dailies
SET status = 'PENDING',
    due_date = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE id = $3 AND status = 'COMPLETED'
`

type ResetCompletedDailyParams struct {
	DueDate pgtype.Timestamptz
	Now     pgtype.Timestamptz
	ID      pgtype.UUID
}

func (q *Queries) ResetCompletedDaily(ctx context.Context, arg ResetCompletedDailyParams) error {
	_, err := q.db.Exec(ctx, resetCompletedDaily, arg.DueDate, arg.Now, arg.ID)
	return err
}

const rollOverPendingDaily = `-- name: RollOverPendingDaily :exec
UPDATE dailies
SET due_date = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE id = $3 AND status = 'PENDING'
`

type RollOverPendingDailyParams struct {
	DueDate pgtype.Timestamptz
	Now     pgtype.Timestamptz
	ID      pgtype.UUID
}

func (q *Queries) RollOverPendingDaily(ctx context.Context, arg RollOverPendingDailyParams) error {
	_, err := q.db.Exec(ctx, rollOverPendingDaily, arg.DueDate, arg.Now, arg.ID)
	return err
}
