// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDamageAmount = `-- name: GetDamageAmount :one
SELECT damage_amount FROM difficulty_rewards WHERE difficulty = $1
`

func (q *Queries) GetDamageAmount(ctx context.Context, difficulty string) (int32, error) {
	row := q.db.QueryRow(ctx, getDamageAmount, difficulty)
	var damage_amount int32
	err := row.Scan(&damage_amount)
	return damage_amount, err
}

const listPendingExpiredDailies = `-- name: ListPendingExpiredDailies :many
SELECT id, user_id, difficulty
FROM dailies
WHERE status = 'PENDING' AND due_date < $1
ORDER BY due_date ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListPendingExpiredDailiesParams struct {
	Before    pgtype.Timestamptz
	BatchSize int32
}

type ListPendingExpiredDailiesRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Difficulty string
}

// Selects up to `limit` PENDING dailies whose due_date has passed,
// locking them with SKIP LOCKED so concurrent worker instances don't collide.
func (q *Queries) ListPendingExpiredDailies(ctx context.Context, arg ListPendingExpiredDailiesParams) ([]ListPendingExpiredDailiesRow, error) {
	rows, err := q.db.Query(ctx, listPendingExpiredDailies, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingExpiredDailiesRow
	for rows.Next() {
		var i ListPendingExpiredDailiesRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailyMissed = `-- name: MarkDailyMissed :exec
UPDATE dailies
SET status = 'MISSED', updated_at = now()
WHERE id = $1 AND status = 'PENDING'
`

// Idempotent: WHERE clause on status = 'PENDING' prevents double-marking.
// NOTE: daily.missed event publication is deferred to #20 (outbox pattern).
func (q *Queries) MarkDailyMissed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDailyMissed, id)
	return err
}
