// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Daily struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DailyHistory struct {
	ID          pgtype.UUID
	DailyID     pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	Status      string
	CompletedAt pgtype.Timestamptz
	MissedAt    pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

type DifficultyReward struct {
	Difficulty      string
	RewardMaterials int32
	DamageAmount    int32
}

type Outbox struct {
	ID          int64
	EventID     pgtype.UUID
	EventType   string
	Payload     []byte
	RequestID   pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type UsersCache struct {
	ID pgtype.UUID
}
