// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDamageAmount(ctx context.Context, difficulty string) (int32, error)
	// Selects up to `limit` PENDING dailies whose due_date has passed,
	// locking them with SKIP LOCKED so concurrent worker instances don't collide.
	ListPendingExpiredDailies(ctx context.Context, arg ListPendingExpiredDailiesParams) ([]ListPendingExpiredDailiesRow, error)
	// Idempotent: WHERE clause on status = 'PENDING' prevents double-marking.
	// NOTE: daily.missed event publication is deferred to #20 (outbox pattern).
	MarkDailyMissed(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
