// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateDailyHistory(ctx context.Context, arg CreateDailyHistoryParams) error
	GetDamageAmount(ctx context.Context, difficulty string) (int32, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// Selects up to `batch_size` COMPLETED dailies whose due_date has passed,
	// locking them with SKIP LOCKED so concurrent worker instances don't collide.
	ListCompletedExpiredDailies(ctx context.Context, arg ListCompletedExpiredDailiesParams) ([]ListCompletedExpiredDailiesRow, error)
	// Selects up to `batch_size` PENDING dailies whose due_date has passed,
	// locking them with SKIP LOCKED so concurrent worker instances don't collide.
	ListPendingExpiredDailies(ctx context.Context, arg ListPendingExpiredDailiesParams) ([]ListPendingExpiredDailiesRow, error)
	ListPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	MarkOutboxPublished(ctx context.Context, id int64) error
	ResetCompletedDaily(ctx context.Context, arg ResetCompletedDailyParams) error
	RollOverPendingDaily(ctx context.Context, arg RollOverPendingDailyParams) error
}

var _ Querier = (*Queries)(nil)
