// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JwtKey struct {
	Kid        string
	PrivateKey []byte
	PublicKey  []byte
	CreatedAt  pgtype.Timestamptz
}

type ProcessedEvent struct {
	EventID     pgtype.UUID
	ProcessedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        int64
	UserID    pgtype.UUID
	Token     string
	FamilyID  pgtype.UUID
	Used      bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
