// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteOldProcessedEvents(ctx context.Context) (int64, error)
	DeleteRefreshTokensByFamilyID(ctx context.Context, familyID pgtype.UUID) error
	DeleteUserByID(ctx context.Context, id pgtype.UUID) error
	GetLatestSigningKey(ctx context.Context) (JwtKey, error)
	GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertProcessedEvent(ctx context.Context, eventID pgtype.UUID) (int64, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (JwtKey, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	MarkRefreshTokenUsed(ctx context.Context, id int64) error
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
