// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteRefreshTokensByFamilyID = `-- name: DeleteRefreshTokensByFamilyID :exec
DELETE FROM refresh_tokens
WHERE family_id = $1
`

func (q *Queries) DeleteRefreshTokensByFamilyID(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByFamilyID, familyID)
	return err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, user_id, token, family_id, used, expires_at, created_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.FamilyID,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token, family_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token, family_id, used, expires_at, created_at
`

type InsertRefreshTokenParams struct {
	UserID    pgtype.UUID
	Token     string
	FamilyID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.Token,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.FamilyID,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens
SET used = true
WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}
