// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing_keys.sql

package database

import (
	"context"
)

const getLatestSigningKey = `-- name: GetLatestSigningKey :one
SELECT kid, private_key, public_key, created_at FROM signing_keys
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSigningKey(ctx context.Context) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getLatestSigningKey)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :one
INSERT INTO signing_keys (kid, private_key, public_key)
VALUES ($1, $2, $3)
RETURNING kid, private_key, public_key, created_at
`

type InsertSigningKeyParams struct {
	Kid        string
	PrivateKey []byte
	PublicKey  []byte
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, insertSigningKey, arg.Kid, arg.PrivateKey, arg.PublicKey)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}
