// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expeditions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getByID = `-- name: GetByID :one
SELECT id, user_id, materials_invested, success_chance, resolve_at, status, created_at, resolved_at FROM expeditions
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id pgtype.UUID) (Expedition, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Expedition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaterialsInvested,
		&i.SuccessChance,
		&i.ResolveAt,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getCurrentByUser = `-- name: GetCurrentByUser :one
SELECT id, user_id, materials_invested, success_chance, resolve_at, status, created_at, resolved_at FROM expeditions
WHERE user_id = $1 AND status = 'IN_FLIGHT'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentByUser(ctx context.Context, userID pgtype.UUID) (Expedition, error) {
	row := q.db.QueryRow(ctx, getCurrentByUser, userID)
	var i Expedition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaterialsInvested,
		&i.SuccessChance,
		&i.ResolveAt,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getLastResolveAt = `-- name: GetLastResolveAt :one
SELECT resolve_at FROM expeditions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastResolveAt(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastResolveAt, userID)
	var resolve_at pgtype.Timestamptz
	err := row.Scan(&resolve_at)
	return resolve_at, err
}

const insertExpedition = `-- name: InsertExpedition :one
INSERT INTO expeditions (
    user_id, materials_invested, success_chance, resolve_at, status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, materials_invested, success_chance, resolve_at, status, created_at, resolved_at
`

type InsertExpeditionParams struct {
	UserID            pgtype.UUID
	MaterialsInvested int32
	SuccessChance     float64
	ResolveAt         pgtype.Timestamptz
	Status            string
}

func (q *Queries) InsertExpedition(ctx context.Context, arg InsertExpeditionParams) (Expedition, error) {
	row := q.db.QueryRow(ctx, insertExpedition,
		arg.UserID,
		arg.MaterialsInvested,
		arg.SuccessChance,
		arg.ResolveAt,
		arg.Status,
	)
	var i Expedition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaterialsInvested,
		&i.SuccessChance,
		&i.ResolveAt,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertExpeditionResult = `-- name: InsertExpeditionResult :one
INSERT INTO expedition_results (
    expedition_id, outcome, reward_summary
) VALUES (
    $1, $2, $3
)
RETURNING id, expedition_id, outcome, reward_summary, created_at
`

type InsertExpeditionResultParams struct {
	ExpeditionID  pgtype.UUID
	Outcome       string
	RewardSummary []byte
}

func (q *Queries) InsertExpeditionResult(ctx context.Context, arg InsertExpeditionResultParams) (ExpeditionResult, error) {
	row := q.db.QueryRow(ctx, insertExpeditionResult, arg.ExpeditionID, arg.Outcome, arg.RewardSummary)
	var i ExpeditionResult
	err := row.Scan(
		&i.ID,
		&i.ExpeditionID,
		&i.Outcome,
		&i.RewardSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listByUser = `-- name: ListByUser :many
SELECT id, user_id, materials_invested, success_chance, resolve_at, status, created_at, resolved_at FROM expeditions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListByUser(ctx context.Context, arg ListByUserParams) ([]Expedition, error) {
	rows, err := q.db.Query(ctx, listByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expedition
	for rows.Next() {
		var i Expedition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaterialsInvested,
			&i.SuccessChance,
			&i.ResolveAt,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
