// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedEvent struct {
	EventID     pgtype.UUID
	ProcessedAt pgtype.Timestamptz
}

type TestTable struct {
	ID   int64
	Name string
}
