// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProcessedEvent = `-- name: InsertProcessedEvent :execrows
INSERT INTO processed_events (event_id) VALUES ($1)
ON CONFLICT (event_id) DO NOTHING
`

func (q *Queries) InsertProcessedEvent(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, insertProcessedEvent, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
