// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ship_cache.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShipCache = `-- name: GetShipCache :one
SELECT user_id, hull_health, materials_balance, updated_at FROM user_ship_state_cache
WHERE user_id = $1
`

func (q *Queries) GetShipCache(ctx context.Context, userID pgtype.UUID) (UserShipStateCache, error) {
	row := q.db.QueryRow(ctx, getShipCache, userID)
	var i UserShipStateCache
	err := row.Scan(
		&i.UserID,
		&i.HullHealth,
		&i.MaterialsBalance,
		&i.UpdatedAt,
	)
	return i, err
}

const seedShipCache = `-- name: SeedShipCache :exec
INSERT INTO user_ship_state_cache (
    user_id, hull_health, materials_balance
) VALUES (
    $1, $2, $3
)
ON CONFLICT (user_id) DO NOTHING
`

type SeedShipCacheParams struct {
	UserID           pgtype.UUID
	HullHealth       int32
	MaterialsBalance int32
}

func (q *Queries) SeedShipCache(ctx context.Context, arg SeedShipCacheParams) error {
	_, err := q.db.Exec(ctx, seedShipCache, arg.UserID, arg.HullHealth, arg.MaterialsBalance)
	return err
}

const upsertShipCache = `-- name: UpsertShipCache :one
INSERT INTO user_ship_state_cache (
    user_id, hull_health, materials_balance
) VALUES (
    $1, $2, $3
)
ON CONFLICT (user_id) DO UPDATE SET
    hull_health = EXCLUDED.hull_health,
    materials_balance = EXCLUDED.materials_balance,
    updated_at = now()
RETURNING user_id, hull_health, materials_balance, updated_at
`

type UpsertShipCacheParams struct {
	UserID           pgtype.UUID
	HullHealth       int32
	MaterialsBalance int32
}

func (q *Queries) UpsertShipCache(ctx context.Context, arg UpsertShipCacheParams) (UserShipStateCache, error) {
	row := q.db.QueryRow(ctx, upsertShipCache, arg.UserID, arg.HullHealth, arg.MaterialsBalance)
	var i UserShipStateCache
	err := row.Scan(
		&i.UserID,
		&i.HullHealth,
		&i.MaterialsBalance,
		&i.UpdatedAt,
	)
	return i, err
}
