// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_table.sql

package database

import (
	"context"
)

const createTestTable = `-- name: CreateTestTable :one
INSERT INTO test_table (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateTestTable(ctx context.Context, name string) (TestTable, error) {
	row := q.db.QueryRow(ctx, createTestTable, name)
	var i TestTable
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteTestTable = `-- name: DeleteTestTable :exec
DELETE FROM test_table
WHERE id = $1
`

func (q *Queries) DeleteTestTable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTestTable, id)
	return err
}

const getTestTable = `-- name: GetTestTable :one
SELECT id, name FROM test_table
WHERE id = $1
`

func (q *Queries) GetTestTable(ctx context.Context, id int64) (TestTable, error) {
	row := q.db.QueryRow(ctx, getTestTable, id)
	var i TestTable
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTestTables = `-- name: ListTestTables :many
SELECT id, name FROM test_table
ORDER BY id
`

func (q *Queries) ListTestTables(ctx context.Context) ([]TestTable, error) {
	rows, err := q.db.Query(ctx, listTestTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestTable
	for rows.Next() {
		var i TestTable
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTestTable = `-- name: UpdateTestTable :one
UPDATE test_table
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateTestTableParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateTestTable(ctx context.Context, arg UpdateTestTableParams) (TestTable, error) {
	row := q.db.QueryRow(ctx, updateTestTable, arg.ID, arg.Name)
	var i TestTable
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
