// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dailies.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDaily = `-- name: CreateDaily :one
INSERT INTO dailies (
    user_id, title, description, difficulty, due_date, time_zone
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at, time_zone
`

type CreateDailyParams struct {
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	TimeZone    string
}

func (q *Queries) CreateDaily(ctx context.Context, arg CreateDailyParams) (Daily, error) {
	row := q.db.QueryRow(ctx, createDaily,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
		arg.TimeZone,
	)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const createDailyHistory = `-- name: CreateDailyHistory :exec
INSERT INTO daily_history (
    daily_id, user_id, title, description, difficulty, due_date, time_zone, status, completed_at, missed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateDailyHistoryParams struct {
	DailyID     pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	TimeZone    string
	Status      string
	CompletedAt pgtype.Timestamptz
	MissedAt    pgtype.Timestamptz
}

func (q *Queries) CreateDailyHistory(ctx context.Context, arg CreateDailyHistoryParams) error {
	_, err := q.db.Exec(ctx, createDailyHistory,
		arg.DailyID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
		arg.TimeZone,
		arg.Status,
		arg.CompletedAt,
		arg.MissedAt,
	)
	return err
}

const createUserCache = `-- name: CreateUserCache :exec
INSERT INTO users_cache (id) VALUES ($1) ON CONFLICT (id) DO NOTHING
`

func (q *Queries) CreateUserCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createUserCache, id)
	return err
}

const deleteDaily = `-- name: DeleteDaily :execrows
DELETE FROM dailies WHERE id = $1 AND user_id = $2
`

type DeleteDailyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteDaily(ctx context.Context, arg DeleteDailyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDaily, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDaily = `-- name: GetDaily :one
SELECT id, user_id, title, description, difficulty, due_date, status, created_at, updated_at, time_zone FROM dailies WHERE id = $1 AND user_id = $2
`

type GetDailyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetDaily(ctx context.Context, arg GetDailyParams) (Daily, error) {
	row := q.db.QueryRow(ctx, getDaily, arg.ID, arg.UserID)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const getDifficultyReward = `-- name: GetDifficultyReward :one
SELECT difficulty, reward_materials, damage_amount FROM difficulty_rewards WHERE difficulty = $1
`

func (q *Queries) GetDifficultyReward(ctx context.Context, difficulty string) (DifficultyReward, error) {
	row := q.db.QueryRow(ctx, getDifficultyReward, difficulty)
	var i DifficultyReward
	err := row.Scan(&i.Difficulty, &i.RewardMaterials, &i.DamageAmount)
	return i, err
}

const listDailies = `-- name: ListDailies :many
SELECT id, user_id, title, description, difficulty, due_date, status, created_at, updated_at, time_zone FROM dailies
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::timestamptz IS NULL OR due_date >= $3)
  AND ($4::timestamptz IS NULL OR due_date < $4)
ORDER BY due_date ASC, created_at ASC
`

type ListDailiesParams struct {
	UserID pgtype.UUID
	Status pgtype.Text
	From   pgtype.Timestamptz
	To     pgtype.Timestamptz
}

func (q *Queries) ListDailies(ctx context.Context, arg ListDailiesParams) ([]Daily, error) {
	rows, err := q.db.Query(ctx, listDailies,
		arg.UserID,
		arg.Status,
		arg.From,
		arg.To,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Daily
	for rows.Next() {
		var i Daily
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyHistory = `-- name: ListDailyHistory :many
SELECT id, daily_id, user_id, title, description, difficulty, due_date, status, completed_at, missed_at, archived_at, time_zone FROM daily_history
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (due_date, archived_at, id) < (
        $2::timestamptz,
        $3::timestamptz,
        $4::uuid
    )
  )
ORDER BY due_date DESC, archived_at DESC, id DESC
LIMIT $5::int
`

type ListDailyHistoryParams struct {
	UserID           pgtype.UUID
	CursorDueDate    pgtype.Timestamptz
	CursorArchivedAt pgtype.Timestamptz
	CursorID         pgtype.UUID
	PageSize         int32
}

// Stable descending keyset page over the (due_date, archived_at, id) tuple.
// `id` is the unique tie-breaker required by the continuation contract. The
// cursor nargs are all-or-nothing: when they are NULL the first page is read.
func (q *Queries) ListDailyHistory(ctx context.Context, arg ListDailyHistoryParams) ([]DailyHistory, error) {
	rows, err := q.db.Query(ctx, listDailyHistory,
		arg.UserID,
		arg.CursorDueDate,
		arg.CursorArchivedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyHistory
	for rows.Next() {
		var i DailyHistory
		if err := rows.Scan(
			&i.ID,
			&i.DailyID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.DueDate,
			&i.Status,
			&i.CompletedAt,
			&i.MissedAt,
			&i.ArchivedAt,
			&i.TimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDifficultyRewards = `-- name: ListDifficultyRewards :many
SELECT difficulty, reward_materials, damage_amount FROM difficulty_rewards
ORDER BY CASE difficulty
    WHEN 'EASY' THEN 1
    WHEN 'MEDIUM' THEN 2
    WHEN 'HARD' THEN 3
    ELSE 4
END
`

// Canonical tier order (EASY, MEDIUM, HARD) so the metadata endpoint is stable.
func (q *Queries) ListDifficultyRewards(ctx context.Context) ([]DifficultyReward, error) {
	rows, err := q.db.Query(ctx, listDifficultyRewards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DifficultyReward
	for rows.Next() {
		var i DifficultyReward
		if err := rows.Scan(&i.Difficulty, &i.RewardMaterials, &i.DamageAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailyComplete = `-- name: MarkDailyComplete :one
UPDATE dailies SET
    status = 'COMPLETED',
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'PENDING'
RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at, time_zone
`

type MarkDailyCompleteParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkDailyComplete(ctx context.Context, arg MarkDailyCompleteParams) (Daily, error) {
	row := q.db.QueryRow(ctx, markDailyComplete, arg.ID, arg.UserID)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const markDailyMissed = `-- name: MarkDailyMissed :one
UPDATE dailies SET
    status = 'MISSED',
    updated_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at, time_zone
`

func (q *Queries) MarkDailyMissed(ctx context.Context, id pgtype.UUID) (Daily, error) {
	row := q.db.QueryRow(ctx, markDailyMissed, id)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const updateDaily = `-- name: UpdateDaily :one
UPDATE dailies SET
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    difficulty = COALESCE($5, difficulty),
    due_date = COALESCE($6, due_date),
    time_zone = COALESCE($7, time_zone),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at, time_zone
`

type UpdateDailyParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
	Difficulty  pgtype.Text
	DueDate     pgtype.Timestamptz
	TimeZone    pgtype.Text
}

func (q *Queries) UpdateDaily(ctx context.Context, arg UpdateDailyParams) (Daily, error) {
	row := q.db.QueryRow(ctx, updateDaily,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
		arg.TimeZone,
	)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}
