// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dailies.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDaily = `-- name: CreateDaily :one
INSERT INTO dailies (
    user_id, title, description, difficulty, due_date
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at
`

type CreateDailyParams struct {
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
}

func (q *Queries) CreateDaily(ctx context.Context, arg CreateDailyParams) (Daily, error) {
	row := q.db.QueryRow(ctx, createDaily,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
	)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDailyHistory = `-- name: CreateDailyHistory :exec
INSERT INTO daily_history (
    daily_id, user_id, title, description, difficulty, due_date, status, completed_at, missed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateDailyHistoryParams struct {
	DailyID     pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description string
	Difficulty  string
	DueDate     pgtype.Timestamptz
	Status      string
	CompletedAt pgtype.Timestamptz
	MissedAt    pgtype.Timestamptz
}

func (q *Queries) CreateDailyHistory(ctx context.Context, arg CreateDailyHistoryParams) error {
	_, err := q.db.Exec(ctx, createDailyHistory,
		arg.DailyID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
		arg.Status,
		arg.CompletedAt,
		arg.MissedAt,
	)
	return err
}

const createUserCache = `-- name: CreateUserCache :exec
INSERT INTO users_cache (id) VALUES ($1) ON CONFLICT (id) DO NOTHING
`

func (q *Queries) CreateUserCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createUserCache, id)
	return err
}

const deleteDaily = `-- name: DeleteDaily :exec
DELETE FROM dailies WHERE id = $1 AND user_id = $2 AND status = 'PENDING'
`

type DeleteDailyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteDaily(ctx context.Context, arg DeleteDailyParams) error {
	_, err := q.db.Exec(ctx, deleteDaily, arg.ID, arg.UserID)
	return err
}

const getDaily = `-- name: GetDaily :one
SELECT id, user_id, title, description, difficulty, due_date, status, created_at, updated_at FROM dailies WHERE id = $1 AND user_id = $2
`

type GetDailyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetDaily(ctx context.Context, arg GetDailyParams) (Daily, error) {
	row := q.db.QueryRow(ctx, getDaily, arg.ID, arg.UserID)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDifficultyReward = `-- name: GetDifficultyReward :one
SELECT difficulty, reward_materials, damage_amount FROM difficulty_rewards WHERE difficulty = $1
`

func (q *Queries) GetDifficultyReward(ctx context.Context, difficulty string) (DifficultyReward, error) {
	row := q.db.QueryRow(ctx, getDifficultyReward, difficulty)
	var i DifficultyReward
	err := row.Scan(&i.Difficulty, &i.RewardMaterials, &i.DamageAmount)
	return i, err
}

const listDailies = `-- name: ListDailies :many
SELECT id, user_id, title, description, difficulty, due_date, status, created_at, updated_at FROM dailies WHERE user_id = $1 ORDER BY due_date ASC, created_at ASC
`

func (q *Queries) ListDailies(ctx context.Context, userID pgtype.UUID) ([]Daily, error) {
	rows, err := q.db.Query(ctx, listDailies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Daily
	for rows.Next() {
		var i Daily
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailyComplete = `-- name: MarkDailyComplete :one
UPDATE dailies SET
    status = 'COMPLETED',
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'PENDING'
RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at
`

type MarkDailyCompleteParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkDailyComplete(ctx context.Context, arg MarkDailyCompleteParams) (Daily, error) {
	row := q.db.QueryRow(ctx, markDailyComplete, arg.ID, arg.UserID)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDailyMissed = `-- name: MarkDailyMissed :one
UPDATE dailies SET
    status = 'MISSED',
    updated_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at
`

func (q *Queries) MarkDailyMissed(ctx context.Context, id pgtype.UUID) (Daily, error) {
	row := q.db.QueryRow(ctx, markDailyMissed, id)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDaily = `-- name: UpdateDaily :one
UPDATE dailies SET
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    difficulty = COALESCE($5, difficulty),
    due_date = COALESCE($6, due_date),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'PENDING'
RETURNING id, user_id, title, description, difficulty, due_date, status, created_at, updated_at
`

type UpdateDailyParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
	Difficulty  pgtype.Text
	DueDate     pgtype.Timestamptz
}

func (q *Queries) UpdateDaily(ctx context.Context, arg UpdateDailyParams) (Daily, error) {
	row := q.db.QueryRow(ctx, updateDaily,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.DueDate,
	)
	var i Daily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
