// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDaily(ctx context.Context, arg CreateDailyParams) (Daily, error)
	CreateDailyHistory(ctx context.Context, arg CreateDailyHistoryParams) error
	CreateTestTable(ctx context.Context, name string) (TestTable, error)
	CreateUserCache(ctx context.Context, id pgtype.UUID) error
	DeleteDaily(ctx context.Context, arg DeleteDailyParams) (int64, error)
	DeleteOldProcessedEvents(ctx context.Context) (int64, error)
	DeleteTestTable(ctx context.Context, id int64) error
	DeleteUserCache(ctx context.Context, id pgtype.UUID) error
	GetDaily(ctx context.Context, arg GetDailyParams) (Daily, error)
	GetDifficultyReward(ctx context.Context, difficulty string) (DifficultyReward, error)
	GetTestTable(ctx context.Context, id int64) (TestTable, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	InsertProcessedEvent(ctx context.Context, eventID pgtype.UUID) (int64, error)
	ListDailies(ctx context.Context, arg ListDailiesParams) ([]Daily, error)
	// Stable descending keyset page over the (due_date, archived_at, id) tuple.
	// `id` is the unique tie-breaker required by the continuation contract. The
	// cursor nargs are all-or-nothing: when they are NULL the first page is read.
	ListDailyHistory(ctx context.Context, arg ListDailyHistoryParams) ([]DailyHistory, error)
	ListPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	ListTestTables(ctx context.Context) ([]TestTable, error)
	MarkDailyComplete(ctx context.Context, arg MarkDailyCompleteParams) (Daily, error)
	MarkDailyMissed(ctx context.Context, id pgtype.UUID) (Daily, error)
	MarkOutboxPublished(ctx context.Context, id int64) error
	UpdateDaily(ctx context.Context, arg UpdateDailyParams) (Daily, error)
	UpdateTestTable(ctx context.Context, arg UpdateTestTableParams) (TestTable, error)
	UpsertUserCache(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
