// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_cache.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserCache = `-- name: DeleteUserCache :exec
DELETE FROM users_cache WHERE id = $1
`

func (q *Queries) DeleteUserCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserCache, id)
	return err
}

const upsertUserCache = `-- name: UpsertUserCache :exec
INSERT INTO users_cache (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) UpsertUserCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertUserCache, id)
	return err
}
