// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expeditions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertExpeditionResult = `-- name: InsertExpeditionResult :exec
INSERT INTO expedition_results (
    expedition_id, outcome, reward_summary
) VALUES (
    $1, $2, $3
)
`

type InsertExpeditionResultParams struct {
	ExpeditionID  pgtype.UUID
	Outcome       string
	RewardSummary []byte
}

func (q *Queries) InsertExpeditionResult(ctx context.Context, arg InsertExpeditionResultParams) error {
	_, err := q.db.Exec(ctx, insertExpeditionResult, arg.ExpeditionID, arg.Outcome, arg.RewardSummary)
	return err
}

const listPendingExpeditions = `-- name: ListPendingExpeditions :many
SELECT id, user_id, materials_invested, success_chance, resolve_at
FROM expeditions
WHERE status = 'IN_FLIGHT' AND resolve_at < $1
ORDER BY resolve_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListPendingExpeditionsParams struct {
	Before    pgtype.Timestamptz
	BatchSize int32
}

type ListPendingExpeditionsRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	MaterialsInvested int32
	SuccessChance     float64
	ResolveAt         pgtype.Timestamptz
}

// Selects up to `batch_size` IN_FLIGHT expeditions whose resolve_at has passed,
// locking them with SKIP LOCKED so concurrent worker instances don't collide.
func (q *Queries) ListPendingExpeditions(ctx context.Context, arg ListPendingExpeditionsParams) ([]ListPendingExpeditionsRow, error) {
	rows, err := q.db.Query(ctx, listPendingExpeditions, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingExpeditionsRow
	for rows.Next() {
		var i ListPendingExpeditionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaterialsInvested,
			&i.SuccessChance,
			&i.ResolveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveExpedition = `-- name: ResolveExpedition :exec
UPDATE expeditions
SET status = $1,
    resolved_at = $2::timestamptz
WHERE id = $3 AND status = 'IN_FLIGHT'
`

type ResolveExpeditionParams struct {
	Status string
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) ResolveExpedition(ctx context.Context, arg ResolveExpeditionParams) error {
	_, err := q.db.Exec(ctx, resolveExpedition, arg.Status, arg.Now, arg.ID)
	return err
}
