// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	InsertExpeditionResult(ctx context.Context, arg InsertExpeditionResultParams) error
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// Selects up to `batch_size` IN_FLIGHT expeditions whose resolve_at has passed,
	// locking them with SKIP LOCKED so concurrent worker instances don't collide.
	ListPendingExpeditions(ctx context.Context, arg ListPendingExpeditionsParams) ([]ListPendingExpeditionsRow, error)
	ListPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	MarkOutboxPublished(ctx context.Context, id int64) error
	ResolveExpedition(ctx context.Context, arg ResolveExpeditionParams) error
}

var _ Querier = (*Queries)(nil)
