// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID          int64
	EventID     pgtype.UUID
	EventType   string
	Payload     []byte
	RequestID   pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type ProcessedEvent struct {
	EventID     pgtype.UUID
	ProcessedAt pgtype.Timestamptz
}

type Ship struct {
	UserID           pgtype.UUID
	HullHealth       int32
	MaterialsBalance int32
	Level            int32
	UpdatedAt        pgtype.Timestamptz
}

type TestTable struct {
	ID   int64
	Name string
}
