// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (event_id, event_type, payload, request_id)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxParams struct {
	EventID   pgtype.UUID
	EventType string
	Payload   []byte
	RequestID pgtype.Text
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.EventID,
		arg.EventType,
		arg.Payload,
		arg.RequestID,
	)
	return err
}

const listPendingOutbox = `-- name: ListPendingOutbox :many
SELECT id, event_id, event_type, payload, request_id, status, created_at, published_at FROM outbox
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET status = 'PUBLISHED', published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
