// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMaterials(ctx context.Context, arg AddMaterialsParams) (Ship, error)
	ApplyDamage(ctx context.Context, arg ApplyDamageParams) (Ship, error)
	CreateShip(ctx context.Context, arg CreateShipParams) error
	CreateTestTable(ctx context.Context, name string) (TestTable, error)
	DeductMaterials(ctx context.Context, arg DeductMaterialsParams) (Ship, error)
	DeleteOldProcessedEvents(ctx context.Context) (int64, error)
	DeleteTestTable(ctx context.Context, id int64) error
	GetByUser(ctx context.Context, userID pgtype.UUID) (Ship, error)
	GetTestTable(ctx context.Context, id int64) (TestTable, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	InsertProcessedEvent(ctx context.Context, eventID pgtype.UUID) (int64, error)
	ListPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	ListTestTables(ctx context.Context) ([]TestTable, error)
	MarkOutboxPublished(ctx context.Context, id int64) error
	Repair(ctx context.Context, arg RepairParams) (Ship, error)
	UpdateTestTable(ctx context.Context, arg UpdateTestTableParams) (TestTable, error)
}

var _ Querier = (*Queries)(nil)
