// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateTestTable(ctx context.Context, name string) (TestTable, error)
	DeleteTestTable(ctx context.Context, id int64) error
	GetTestTable(ctx context.Context, id int64) (TestTable, error)
	ListTestTables(ctx context.Context) ([]TestTable, error)
	UpdateTestTable(ctx context.Context, arg UpdateTestTableParams) (TestTable, error)
}

var _ Querier = (*Queries)(nil)
