// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ships.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMaterials = `-- name: AddMaterials :one
UPDATE ships SET materials_balance = materials_balance + $2, updated_at = now() WHERE user_id = $1 RETURNING user_id, hull_health, materials_balance, level, updated_at
`

type AddMaterialsParams struct {
	UserID           pgtype.UUID
	MaterialsBalance int32
}

func (q *Queries) AddMaterials(ctx context.Context, arg AddMaterialsParams) (Ship, error) {
	row := q.db.QueryRow(ctx, addMaterials, arg.UserID, arg.MaterialsBalance)
	var i Ship
	err := row.Scan(
		&i.UserID,
		&i.HullHealth,
		&i.MaterialsBalance,
		&i.Level,
		&i.UpdatedAt,
	)
	return i, err
}

const applyDamage = `-- name: ApplyDamage :one
UPDATE ships SET hull_health = GREATEST(0, hull_health - $2), updated_at = now() WHERE user_id = $1 RETURNING user_id, hull_health, materials_balance, level, updated_at
`

type ApplyDamageParams struct {
	UserID     pgtype.UUID
	HullHealth int32
}

func (q *Queries) ApplyDamage(ctx context.Context, arg ApplyDamageParams) (Ship, error) {
	row := q.db.QueryRow(ctx, applyDamage, arg.UserID, arg.HullHealth)
	var i Ship
	err := row.Scan(
		&i.UserID,
		&i.HullHealth,
		&i.MaterialsBalance,
		&i.Level,
		&i.UpdatedAt,
	)
	return i, err
}

const createShip = `-- name: CreateShip :exec
INSERT INTO ships (user_id, hull_health, materials_balance, level)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO NOTHING
`

type CreateShipParams struct {
	UserID           pgtype.UUID
	HullHealth       int32
	MaterialsBalance int32
	Level            int32
}

func (q *Queries) CreateShip(ctx context.Context, arg CreateShipParams) error {
	_, err := q.db.Exec(ctx, createShip,
		arg.UserID,
		arg.HullHealth,
		arg.MaterialsBalance,
		arg.Level,
	)
	return err
}

const getByUser = `-- name: GetByUser :one
SELECT user_id, hull_health, materials_balance, level, updated_at FROM ships WHERE user_id = $1
`

func (q *Queries) GetByUser(ctx context.Context, userID pgtype.UUID) (Ship, error) {
	row := q.db.QueryRow(ctx, getByUser, userID)
	var i Ship
	err := row.Scan(
		&i.UserID,
		&i.HullHealth,
		&i.MaterialsBalance,
		&i.Level,
		&i.UpdatedAt,
	)
	return i, err
}

const repair = `-- name: Repair :one
UPDATE ships SET hull_health = LEAST(100, hull_health + $3), materials_balance = materials_balance - $2, updated_at = now() WHERE user_id = $1 RETURNING user_id, hull_health, materials_balance, level, updated_at
`

type RepairParams struct {
	UserID           pgtype.UUID
	MaterialsBalance int32
	HullHealth       int32
}

func (q *Queries) Repair(ctx context.Context, arg RepairParams) (Ship, error) {
	row := q.db.QueryRow(ctx, repair, arg.UserID, arg.MaterialsBalance, arg.HullHealth)
	var i Ship
	err := row.Scan(
		&i.UserID,
		&i.HullHealth,
		&i.MaterialsBalance,
		&i.Level,
		&i.UpdatedAt,
	)
	return i, err
}
